
import Header from "@/components/header";
import Footer from "@/components/footer";

import type { Metadata } from "next";
import { Poppins, Volkhov } from "next/font/google";
import "./globals.css";  
import "leaflet/dist/leaflet.css"; 
import "leaflet.markercluster/dist/MarkerCluster.css";
import "leaflet.markercluster/dist/MarkerCluster.Default.css";



const volkhov = Volkhov({
  variable: "--font-volkhov",
  subsets: ["latin"],
  weight: ["400", "700"]
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Touraroo",
  description: "Generated by CTU-TouraroInsightCrew ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${volkhov.variable} ${poppins.variable} antialiased font-poppins`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
